services:
  php-apache-environment:
    container_name: php-apache
    image: php:8.3-apache
    volumes:
      - ./php:/var/www/html/
      - ./css:/var/www/html/css
    ports:
      - 8000:80 ## or 8315:80
